/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Flammulina_filiformis.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Enoki_with_hole2: THREE.Mesh
  }
  materials: {
    cream: THREE.MeshStandardMaterial
  }
}

export function FlammulinaFiliformis(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Flammulina_filiformis.glb') as GLTFResult

  const yOffset = -0.85

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.cream} position={[0, 0.132 + yOffset, 0]} scale={0.923} />
      <mesh geometry={nodes.Enoki_with_hole2.geometry} material={materials.cream} position={[0, yOffset, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Flammulina_filiformis.glb')
