/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/gameboy_keycap.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    GameboyBody: THREE.Mesh
    GameboyButtonA: THREE.Mesh
    GameboyButtonB: THREE.Mesh
    GameboyButtonDPad: THREE.Mesh
    GameboyButtonStart: THREE.Mesh
    GameboyButtonSelect: THREE.Mesh
    GameboyBodyTop: THREE.Mesh
    Cartridge: THREE.Mesh
  }
  materials: {
    Cream: THREE.MeshStandardMaterial
    Burgundy: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Grey: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
  }
}

export function GameboyKeycap(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/gameboy_keycap.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.GameboyBody.geometry} material={materials.Cream} position={[-1.438, 0, -2.226]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.GameboyButtonA.geometry} material={materials.Burgundy} position={[3.596, 3.338, 5.564]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.GameboyButtonB.geometry} material={materials.Burgundy} position={[-1.438, 0, -2.226]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.GameboyButtonDPad.geometry} material={materials.Black} position={[-1.438, 0, -2.226]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.GameboyButtonStart.geometry} material={materials.Grey} position={[-1.438, 0, -2.226]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.GameboyButtonSelect.geometry} material={materials.Grey} position={[-1.438, 0, -2.226]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.GameboyBodyTop.geometry} material={materials.Grey} position={[-1.438, 0, -2.226]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.Cartridge.geometry} material={materials.Yellow} position={[-1.462, 3.309, -4.426]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/models/gameboy_keycap.glb')
