/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/Morchellaceae_Morchella.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    CapTexture: THREE.Mesh
    CqpInside: THREE.Mesh
    Stipe: THREE.Mesh
  }
  materials: {
    DesertYellow: THREE.MeshStandardMaterial
    DesertYellowDark: THREE.MeshStandardMaterial
    Cream: THREE.MeshStandardMaterial
  }
}

export function MorchellaEsculenta(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Morchella_esculenta.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.CapTexture.geometry} material={materials.DesertYellow} position={[0, 8, 0]} scale={0.5} />
      <mesh geometry={nodes.CqpInside.geometry} material={materials.DesertYellowDark} position={[0, 8, 0]} scale={0.96 * 0.5} />
      <mesh geometry={nodes.Stipe.geometry} material={materials.Cream} position={[0.28, 4.819, -0.144]} scale={[0.769*0.5, 0.883*0.5, 0.769*0.5]} />
    </group>
  )
}

useGLTF.preload('/models/Morchella_esculenta.glb')
